# Generated by Django 4.0.5 on 2022-06-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('cod_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('cnh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('marca', models.CharField(max_length=100)),
                ('veiculo', models.CharField(max_length=200)),
                ('km_troca_oleo', models.FloatField(verbose_name='km Troca de óleo')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('hora_saida', models.TimeField()),
                ('km_saida', models.FloatField()),
                ('destino', models.CharField(max_length=200)),
                ('data_retorno', models.DateField()),
                ('hora_retorno', models.TimeField()),
                ('km_retorno', models.FloatField()),
                ('km_percorrido', models.FloatField()),
                ('cod_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleDeVeiculos.motorista')),
                ('cod_veiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleDeVeiculos.veiculos')),
            ],
        ),
    ]
