# Generated by Django 4.0.5 on 2022-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleDeVeiculos', '0002_rename_veiculos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='km_percorrido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='controle',
            name='km_retorno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='controle',
            name='km_saida',
            field=models.IntegerField(),
        ),
    ]
